
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Comentario_Multi_Cierra = 17;
  public static final int Punto_Coma = 10;
  public static final int Suma = 14;
  public static final int Numero = 4;
  public static final int ERROR = 22;
  public static final int Identificador = 3;
  public static final int Asterizco = 13;
  public static final int Coma = 9;
  public static final int Or = 12;
  public static final int Cadena = 20;
  public static final int EOF = 0;
  public static final int Interrogacion = 15;
  public static final int CONJ = 2;
  public static final int Linea = 19;
  public static final int Porcentaje = 18;
  public static final int error = 1;
  public static final int Dos_Puntos = 11;
  public static final int Guion = 7;
  public static final int Punto = 8;
  public static final int Asignacion = 21;
  public static final int Comentario_Multi_Abre = 16;
  public static final int Llave_Cierra = 6;
  public static final int Llave_Abre = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "Identificador",
  "Numero",
  "Llave_Abre",
  "Llave_Cierra",
  "Guion",
  "Punto",
  "Coma",
  "Punto_Coma",
  "Dos_Puntos",
  "Or",
  "Asterizco",
  "Suma",
  "Interrogacion",
  "Comentario_Multi_Abre",
  "Comentario_Multi_Cierra",
  "Porcentaje",
  "Linea",
  "Cadena",
  "Asignacion",
  "ERROR"
  };
}

